### ISSUE TITLE
Multiple tests for a patient not working correctly

### ISSUE THREAD

**Issue by lordpomeroy** [ImisDevelopers/1_011_a_infektionsfall_uebermittellung#317] opened 2020-05-15 15:54 UTC
**Problem**
If a patient has multiple tests assigned the test results are not assigned correctly.

**Steps to reproduce**
- Assign a probe to a user
- Add the test result for this test
- Assign a new probe to the user
- Add the test result for the second test (choose a different from the first one)

**Expected**
- In "Falldaten" both tests have their respective status

**Actual**
- In "Falldaten" the first test has the second test's status and the second test is in status "Test eingereicht"
- "Verlauf" and the status Badge at the Top are correct

**Comment by jabrandes** [comment] 2020-05-15 21:10
This might be a problem related to caching. I could only reproduce the error as specified when accessing the patient's details page after the first test concluded (in my case with positive result) and before the second test was registered. After the second test has been entered (negative result) when the event's view (*Verlauf*) is opened, only the data of the first test is shown:

![image](https://user-images.githubusercontent.com/16663164/82096301-f4bc5980-9700-11ea-8d32-fc3f5148e564.png)

After a forced reload of the page:

![image](https://user-images.githubusercontent.com/16663164/82096352-17e70900-9701-11ea-93a0-e5d2efa02e18.png)

**Comment by lordpomeroy** [comment] 2020-05-16 08:35
Yes that is an issue. But this ticket is about the "Falldaten" view. There the test results are shown incorrectly. That the cache is not working correctly is another point. I will create an issue for that one as well later today.

**Comment by jabrandes** [comment] 2020-05-16 16:14
If recalling my testing from yesterday correctly, I haven't been able to reproduce the problem as described while adhering to the *steps to reproduce* section. Could you please verify that it's still an issue? If the problem is still existent, it would be quite helpful for me to see a screenshot of the *Falldaten* view with the incorrect data marked.

**Comment by Jochen-Sch** [comment] 2020-05-18 12:14
While cashing issue still exists, the incorrect assigned test result cannot be reproduced with the current state any longer. Executed different test including different sequences of test creation and test results do not show that behavior any more. Therefore closing the issue

**Closed** 2020-05-18 12:14 UTC
Labels: bug, part-client, prio-high!!!
