### ISSUE TITLE
Dialog Navigation: Patient List <> Patient Details

### ISSUE THREAD

**Issue by Jochen-Sch** [ImisDevelopers/1_011_a_infektionsfall_uebermittellung#372] opened 2020-05-20 14:42 UTC
When accessing patient details from the patient list the 'back' button shall lead to the patient list with the same search criteria that where used before navigating to the patient details with the same loaded page of the result set.

**Comment by JonasCir** [comment] 2020-05-21 08:39
Duplicate of #347

**Closed by JonasCir** 2020-05-21 08:39 UTC
Labels: duplicate, f-patient-details, f-patient-list, feature, part-client
